# Generated by Django 4.2.2 on 2023-06-27 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branch", "0001_initial"),
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="company.company",
            ),
        ),
    ]
