# Generated by Django 4.2.2 on 2023-07-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('asset_tag', models.CharField(blank=True, max_length=255, null=True)),
                ('model_id', models.IntegerField(null=True)),
            ],
        ),
    ]
