# Generated by Django 4.2.2 on 2023-07-22 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Device',
        ),
    ]
