# Generated by Django 4.2.2 on 2023-07-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('asset_tag', models.CharField(blank=True, max_length=255, null=True)),
                ('model_id', models.IntegerField(null=True)),
                ('serial_no', models.CharField(max_length=191, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('asset_eol_date', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('order_number', models.CharField(blank=True, max_length=191, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/devices/')),
                ('physical', models.BooleanField(default=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('rtd_location_id', models.IntegerField(blank=True, null=True)),
                ('warranty_months', models.IntegerField(blank=True, null=True)),
                ('depreciate', models.BooleanField(blank=True, null=True)),
                ('supplier_id', models.IntegerField(blank=True, null=True)),
                ('last_checkout', models.DateTimeField(blank=True, null=True)),
                ('expected_checkin', models.DateField(blank=True, null=True)),
                ('assigned_type', models.CharField(blank=True, max_length=191, null=True)),
                ('last_audit_date', models.DateTimeField(blank=True, null=True)),
                ('next_audit_date', models.DateField(blank=True, null=True)),
                ('byod', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'device',
            },
        ),
    ]
