# Generated by Django 4.2.2 on 2023-07-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_alter_device_asset_tag_alter_device_assigned_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='asset_eol_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
