# Generated by Django 4.2.2 on 2023-07-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_alter_device_asset_eol_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='order_number',
            field=models.TextField(blank=True, null=True),
        ),
    ]
