# Generated by Django 4.2.2 on 2023-07-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_alter_device_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='order_number',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
    ]
