# Generated by Django 4.2.2 on 2023-07-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0005_alter_device_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='model_id',
            field=models.IntegerField(null=True),
        ),
    ]
