# Generated by Django 4.2.2 on 2023-07-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0006_alter_device_model_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='comments',
            field=models.TextField(null=True),
        ),
    ]
