# Generated by Django 4.2.2 on 2023-07-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0007_alter_device_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
