# Generated by Django 4.2.2 on 2023-06-27 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company", old_name="is_active", new_name="company_active",
        ),
    ]
