# Generated by Django 4.2.2 on 2023-06-15 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(name="company", table="company",),
    ]
