# Generated by Django 4.2.2 on 2023-06-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_alter_company_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="email",
            field=models.EmailField(default="test@email.com", max_length=250),
            preserve_default=False,
        ),
    ]
