# Generated by Django 4.2.2 on 2023-06-27 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("branch", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="branch", old_name="is_active", new_name="branch_active",
        ),
    ]
