# Generated by Django 4.2.2 on 2023-07-10 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('license_key', models.CharField(max_length=191, null=True)),
                ('license_name', models.CharField(max_length=120)),
                ('license_email', models.CharField(max_length=200)),
                ('license_allocated', models.CharField(max_length=191)),
                ('license_type', models.CharField(max_length=120)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_order', models.CharField(blank=True, max_length=191, null=True)),
                ('seats', models.CharField(max_length=191)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('order_number', models.CharField(blank=True, max_length=191, null=True)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('supplier_id', models.IntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company')),
            ],
            options={
                'db_table': 'software',
            },
        ),
    ]
