# Generated by Django 4.2.2 on 2023-07-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='license_allocated',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='license_email',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='license_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='seats',
            field=models.IntegerField(max_length=191),
        ),
    ]
