# Generated by Django 4.2.2 on 2023-07-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0002_alter_software_license_allocated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='seats',
            field=models.IntegerField(),
        ),
    ]
