# Generated by Django 4.2.2 on 2023-07-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0003_alter_software_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software',
            name='order_number',
        ),
        migrations.AlterField(
            model_name='software',
            name='license_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
